# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d20e81e43dca716fe879b1dd97a5d6dceb8db59bba482bb0c9dbfefb098a6f50878199219766ae11b05cb8e04ffe338451ce123698f33ada2a0385bbe1882abe

test:
  secret_key_base: 75570db5901afefef75e3f9d742d6a48608fcb378fa25bcdfe7a076bc07f78047b1ed6942ab35e4775e0d958a18f4206afb4ef5811760f53e877e2ab95e3e53b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
